<?php

/**
 * QW03 / TODO.md item 8: every page declared in getPages() that is not a
 * redirect or a noindex/error page must be declared in the generated
 * sitemap. This is what should have caught senior-tech.html silently
 * going missing from sitemap.xml. Run: php tests/sitemap-consistency.test.php
 */

require_once __DIR__ . '/../src/sitemap.php';

$failures = 0;

try {
    assertSitemapConsistency();
    echo "  \xE2\x9C\x93 Every non-excluded getPages() entry has a sitemap lastmod\n";
} catch (RuntimeException $e) {
    fwrite(STDERR, '  ✗ ' . $e->getMessage() . "\n");
    $failures++;
}

// Belt-and-suspenders: also check the actually-generated XML, not just
// the lastmod table, so a bug in buildSitemapXml() itself would be caught
// too, not only a missing data entry.
if ($failures === 0) {
    $xml = buildSitemapXml();
    preg_match_all('#<loc>([^<]+)</loc>#', $xml, $matches);
    $declaredLocs = array_flip($matches[1]);

    $exclusions = getSitemapExclusions();
    $missingFromXml = [];
    $wronglyPresent = [];

    foreach (getPages() as $page) {
        $output = $page[0];
        $loc = 'https://www.matthieu-viel.fr' . sitemapUrlPath($output);
        $excluded = isset($exclusions[$output]);

        if (!$excluded && !isset($declaredLocs[$loc])) {
            $missingFromXml[] = $output;
        }

        if ($excluded && isset($declaredLocs[$loc])) {
            $wronglyPresent[] = $output;
        }
    }

    if ($missingFromXml !== []) {
        fwrite(STDERR, '  ✗ Missing from generated sitemap: ' . implode(', ', $missingFromXml) . "\n");
        $failures++;
    } else {
        echo "  \xE2\x9C\x93 Every non-excluded page appears in the generated sitemap XML\n";
    }

    if ($wronglyPresent !== []) {
        fwrite(STDERR, '  ✗ Excluded pages leaked into the sitemap: ' . implode(', ', $wronglyPresent) . "\n");
        $failures++;
    } else {
        echo "  \xE2\x9C\x93 No excluded page (redirect/noindex/error) leaked into the sitemap\n";
    }
}

// The generated XML is only useful if it is what actually ships. sitemap.xml
// is committed and regenerated by src/generate-sitemap.php, so a routing
// change made without rerunning it would otherwise pass every check above.
if ($failures === 0) {
    $onDisk = file_get_contents(__DIR__ . '/../sitemap.xml');

    if ($onDisk !== buildSitemapXml()) {
        fwrite(STDERR, "  \xE2\x9C\x97 sitemap.xml is stale. Run: php src/generate-sitemap.php\n");
        $failures++;
    } else {
        echo "  \xE2\x9C\x93 sitemap.xml on disk matches what routes.php generates\n";
    }
}

if ($failures > 0) {
    fwrite(STDERR, "\n❌ Sitemap consistency test failed.\n");
    exit(1);
}

echo "\n✅ Sitemap consistency test passed.\n";
